# -*- coding: utf-8 -*-
"""Product review analysis project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqoqgY02NOgr8AA-_7-y1m78AQK_VPEU
"""

!pip install sentence-transformers

from transformers import pipeline
import pandas as pd
#load sentiment analysis model
sentiment = pipeline("sentiment-analysis") # Changed 'sentiment analysis' to 'sentiment-analysis' for common practice
#sample product review (you can change only this text later)
reviews = """ the laptop starts quickly and works smoothly for daily tasks.
THe screen quality is clear and good for watching vedois .
Battery backup is average and needs charging often.
The fan makes noise when many apps are running.
overall,it is a good laptop for students but not for gamming. """
#split review into sentences
sentences = reviews.split(".")
pros = []
cons = []
for s in sentences:
  s = s.strip()
  if s == "": # Changed ' ' to '' for empty string check
    continue
  result = sentiment(s)[0] # Corrected 'sentimnet' to 'sentiment'
  if result["label"]  == "POSITIVE":
    pros.append(s)
  elif result["label"] == "NEGATIVE":
    cons.append(s)
#take only 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]
#create a table
df = pd.DataFrame({"pros":pros,"cons":cons})
df