# -*- coding: utf-8 -*-
"""sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qKLzIPlOQigtwDBArrC_1uJd0xdlLHVD
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer , util
#load the model
model = SentenceTransformer('all-MiniLM-L6-v2')
#take the input ffrom the user
text1 = input("enter the text1: ")
text2 = input("enter the text2: ")
#convert text to embeddings
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)
#calculate the similarity
similarity = util.cos_sim(embedding1,embedding2)
#show result
print("\n similarity score:" , round(float(similarity), 2))
if similarity > 0.75:
  print("similarity level: high")
elif similarity > 0.4:
  print("similarity level: medium")
else:
  print("similariy level: low")