# -*- coding: utf-8 -*-
"""Time Table Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KqI8FaDstLR_Za3E1vFMSZ1a96Cf0N82
"""

#time table generator
import pandas as pd
import random
print("TIME TABLE GENERATOR");

#user inputs
subeject_input = input("enter subjects:")
days_input = input("enter days:")
periods_per_day = int(input("enter no of periods per day:"))

#prosses inputs
subjects = [s.strip() for s in subejects_input.split(',') if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]

#validation
if len(subjects) == 0 or len(days) == 0 or periods_per_day <= 0:
  print("Invalid input. plese  try again.")
else :
  timetable = {}
  for day in days:
    timetable[day] = random.choices(subjects , k = periods_per_day)

#create data frame
df = pd.DataFrame(timetable)
df.index = [f"Period {i+1}" for i in range(periods_per_day)]
print("\n TIME TABLE GENERATED SUCCESSFULLY\n")
display(df)

#save time table
df.to_csv("timetable.csv")
print("\n time table saved as timetable.csv")